name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Install Dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Remove Previous Deploy Folder
        run: rm -rf /var/www/codective.ir/

      - name: Create Deploy Folder
        run: mkdir -p /var/www/codective.ir/

      - name: Move Built Files to Deploy Folder
        run: mv dist/* /var/www/codective.ir/
